apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: hashicorp/http-echo
        args:
        - "-text=Order Service Connected to Product + DB"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
          requests:
            cpu: "250m"
            memory: "250Mi"